import Image from 'next/image';
import Link from 'next/link';
import styles from './style.module.css';
import { useState } from 'react';
import produtos from '@/utils/produtos';
import Head from 'next/head';
import categoria from '@/utils/categoria';
import Categorias from '@/components/categorias/categorias';
import topCategorias from '@/utils/topCategorias';

const Produtos = () => {
    const [display, setDisplay] = useState('none')
    const [id, setId] = useState(0)
    const [count, setCount] = useState(0)
    const [cate, setCate] = useState('')

    return (
        <div className={styles.container}>
            <Head>
                <title>Produtos - Doutor Drywall</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <div className={styles.titulo}>
                <h1>PRODUTOS</h1>
                <h3>Conheça nossa diversidade de produtos</h3>
                <div style={{ display: 'none' }}>{count}</div>
            </div>
            <div className={styles.produtosSection}>
                <Categorias cateId={''} />
                <div className={styles.produtosArea}>
                    <div className={styles.categoriaArea}>
                        {topCategorias.map((item, index) => (
                            <div className={styles.item} key={index} >
                                <Link href={item.link} key={index}>
                                    <div className={styles.produtoImg} >
                                        <Image src={item.img} alt="" />
                                    </div>
                                    <div className={styles.categoriaName}>
                                        <div>{item.name}</div>
                                    </div>
                                </Link>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

        </div >
    )
}

export default Produtos;