import Image from 'next/image';
import Link from 'next/link';
import styles from './style.module.css';
import { useState } from 'react';
import produtos from '@/utils/produtos';
import Head from 'next/head';
import categoria from '@/utils/categoria';
import { useRouter } from 'next/router';
import Categorias from '@/components/categorias/categorias';

const Produtos = () => {
    const [display, setDisplay] = useState('none')
    const [id, setId] = useState(0)
    const router = useRouter()
    const [qtd, setQtd] = useState(0)

    const cateId = router.query.cateId

    const page = () => {
        for (let i = 0; i < produtos.length; i++) {
            produtos[i].categoria == cateId ? setQtd(qtd + 1) : ''
        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Produtos - Doutor Drywall</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.titulo}>
                <h1>PRODUTOS</h1>
                <h3>Conheça nossa diversidade de produtos de {cateId}</h3>
            </div>
            <div className={styles.caminho}><a href='/'>Home</a> > <a href='/produtos'>Produtos</a> > {cateId}</div>
            <div className={styles.produtosSection}>
                <Categorias />
                <div className={styles.produtosArea}>
                    <div className={styles.categoriaAtual}>
                        {cateId}
                        <span>{0} itens encontrados</span>
                    </div>
                    <div className={styles.produtoList}>
                        {produtos.map((item, index) => (
                            <>
                                {item.categoria === cateId || item.parceiro === cateId ?

                                    <div className={styles.item} key={index} onMouseMove={() => { setDisplay('flex'), setId(index) }} onMouseOut={() => setDisplay('none')}>
                                        <a href={`/produtos/item/${index}`}><div className={styles.produtoImg}>
                                            <img src={item.img} alt="" />
                                        </div>
                                            <div className={styles.produtoName}>
                                                <div>{item.name}</div>
                                            </div></a>
                                        <div className={styles.contatoArea}>
                                            {id >= 0 && index === id ?
                                                <div className={styles.zap} style={{ display: display }}>
                                                    <div>Entrar em Contato</div>
                                                    <img src="/images/social/whatsapp.png" alt="" />
                                                </div>
                                                :
                                                ''}
                                        </div>
                                    </div>
                                    : ''}
                            </>
                        ))}
                    </div>
                    <div onClick={() => page()}>olá ({qtd})</div>
                </div>
            </div>

        </div>
    )
}

export default Produtos;