const categoria = [
    { name: 'Drywall', categoria: 'Drywall', link: '/produtos/categoria/Drywall', img: '/images/drywall.jpg' },
    { name: 'Pintura', link: '/produtos/categoria/Pintura', img: '/images/pintura.jpg' },
    { name: 'Silicones', link: '/produtos/categoria/Silicone', img: '/images/silicone.jpg' },
    { name: "Caixas D'aguas", link: '/produtos/categoria/caixaDagua', img: '/images/caixaDagua.jpg' },
    { name: 'Tintas', categoria: 'Tintas e Acessórios', link: '/produtos/categoria/Tintas', img: '/images/tintas.jpg' },
    { name: 'Verniz', categoria: 'Tintas e Acessórios', link: '/produtos/categoria/Verniz', img: '/images/verniz.jpg' },
    { name: 'Resinas', categoria: 'Tintas e Acessórios', link: '/produtos/categoria/Resinas', img: '/images/resina.jpg' },
    { name: 'Fundo Preparador', categoria: 'Tintas e Acessórios', link: '/produtos/categoria/Fundo-Preparador', img: '/images/preparador.jpeg' },
    //{ name: 'Cimentos', categoria: 'Materiais de Construção', link: '/produtos/categoria/Cimento', img: '/images/limpeza.jpg' },
    { name: 'Argamassas', categoria: 'Materiais de Construção', link: '/produtos/categoria/Argamassa', img: '/images/argamassa.jpg' },
    { name: 'Fixação', categoria: 'Materiais de Construção', link: '/produtos/categoria/Fixação', img: '/images/fixar.jpg' },
    { name: 'Conexões', categoria: 'Tubos e Conexões', link: '/produtos/categoria/Conexões', img: '/images/conexão.jpeg' },
    { name: 'Tubos', categoria: 'Tubos e Conexões', link: '/produtos/categoria/Tubos', img: '/images/tubo.avif' },
    { name: 'Impermeabilizante', link: '/produtos/categoria/Impermeabilizante', img: '/images/ipermeabilizante.jpg' },
    { name: 'Abrasivos', categoria: 'Tintas e Acessórios', link: '/produtos/categoria/Abrasivos', img: '/images/abrasivo.png' },
    { name: 'Segurança', categoria: 'Tintas e Acessórios', link: '/produtos/categoria/Segurança', img: '/images/segurança.jpg' },
    { name: 'Louças', categoria: 'Acessórios', link: '/produtos/categoria/Louças', img: '/images/louça.jpg' },
    { name: 'Hidráulica', categoria: 'Acessórios', link: '/produtos/categoria/Hidráulica', img: '/images/hidraulica.jpg' },
    { name: 'Elétrica', categoria: 'Acessórios', link: '/produtos/categoria/Elétrica', img: '/images/eletrica.jpg' },
    { name: 'Mantas', categoria: 'Materiais de Construção', link: '/produtos/categoria/Mantas', img: '/images/manta.jpg' },
    { name: 'Massas Corridas', categoria: 'Tintas e Acessórios', link: '/produtos/categoria/Massas-Corridas', img: '/images/massaCorrida.jpg' },
    { name: 'Lixeira', categoria: 'Utilidades', link: '/produtos/categoria/Lixeira', img: '/images/lixeira.jpg' },
    { name: 'Limpeza', categoria: 'Utilidades', link: '/produtos/categoria/Limpeza', img: '/images/limpeza.jpg' },
    { name: 'Acessórios', categoria: 'Tintas e Acessórios', link: '/produtos/categoria/Tinta-Acessorios', img: '/images/acessorio.jpg' },
    { name: 'Ipermeabilizantes', categoria: 'Tintas e Acessórios', link: '/produtos/categoria/Ipermeabilizantes', img: '/images/ipermeabilizante.jpg' },
    { name: 'Ferragens', categoria: 'Materiais de Construção', link: '/produtos/categoria/Ferragens', img: '/images/ferragem.jpg' },
    
]

export default categoria;