import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Footer from '@/components/footer'
import Parceiros from '@/components/parceiros'
import Carousel from '@/components/carousel'
import Produtos from '@/components/produtos'
import Categorias from '@/components/categorias'
import PosCategoria from '@/components/local'
import Local from '@/components/local'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="main">
      <Head>
        <title>Doutor Drywall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Carousel />
      <Parceiros />
      <Produtos />
      <Categorias />
      <Local />
    </div>
  )
}
